builds:
  -
    binary: graboid
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X m-X main.Version={{.Version}} -X main.BuildTime={{.Date}}

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: amd64
    darwin: macOS
    linux: linux
    windows: win

brew:
  github:
    owner: blacktop
    name: homebrew-tap
  folder: Formula
  homepage: "https://github.com/blacktop/graboid"
  description: "Clientless docker image downloader."
  test: |
    system "#{bin}/graboid --version"
