name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod download
    - name: Download
      run: CGO_ENABLED=0 go run main.go blacktop/zeek
    - name: Tag
      run: CGO_ENABLED=0 go run main.go tags blacktop/zeek      
